apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 7
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: gcr.io/grounded-plane-228500/shopify-challenge-image:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
